- name: Remove manjaro-zsh-configs
  become: true
  pacman:
    name: manjaro-zsh-configs
    state: absent
    extra_args: --recursive
  tags:
    - install
    - never

- name: Remove system default dotfiles
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: absent
  with_items:
    - .zshrc
    - .i3
    - .Xresources
  tags:
    - install
    - never
