- name: Install stow
  become: true
  pacman: name=stow

- name: Cloning dotfiles
  git:
    repo: git@github.com:r3k4mn14r/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Linking dotfiles
  shell: "stow -t {{ lookup('env', 'HOME') }} -d {{ lookup('env', 'HOME') }}/.dotfiles/stow {{ item }}"
  with_items:
    - zsh
    - tmux
    - nvim
    - ipython
    - i3
    - urxvt
