- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "8102483+r3k4mn14r@users.noreply.github.com"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "r3k4mn14r"
- name: Set default branch to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
