- name: Install neovim
  become: true
  pacman:
    name: neovim
  tags:
    - install
    - neovim

- name: Create required nvim directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload"
    state: directory
    mode: '0755' 
  tags:
    - install
    - neovim

- name: Clone vim-plug
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
  tags:
    - install
    - neovim
