- name: Setup dev tools
  become: true
  pacman: 
    name: tmux,tldr,ripgrep,fd,xclip,git,xterm
  tags:
    - install
    - tools

- name: Install terminal fonts
  command: yay -S nerd-fonts-source-code-pro --noconfirm
  tags:
    - install

- name: Install brave browser
  command: yay -S brave-bin --noconfirm
  tags:
    - install

- name: Install ghq
  command: yay -S ghq --noconfirm
  tags:
    - install
