- name: Install zsh
  become: true
  pacman: name=zsh

- name: Change default shell to zsh
  become: true
  shell: chsh -s "$(which zsh)" "{{ lookup('env', 'USER') }}"

- name: Install powerlevel10k prompt
  shell: yay -S zsh-theme-powerlevel10k-git --noconfirm
