- name: Install zsh
  become: true
  pacman:
    name: zsh
  tags:
    - install
    - zsh

- name: Change default shell to zsh
  become: true
  shell: chsh -s "$(which zsh)" "{{ lookup('env', 'USER') }}"
  tags:
    - install
    - zsh

- name: Install powerlevel10k prompt
  command: yay -S zsh-theme-powerlevel10k-git --noconfirm
  tags:
    - install
    - zsh

- name: Install zsh-completions
  command: yay -S zsh-completions-git --noconfirm
  tags:
    - install
    - zsh

- name: Install zsh-autosuggestions
  command: yay -S zsh-autosuggestions-git --noconfirm
  tags:
    - install
    - zsh

- name: Install zsh-syntax-highlighting
  command: yay -S zsh-syntax-highlighting-git --noconfirm
  tags:
    - install
    - zsh
